config/routes.rb
SampleApp::Application.routes.draw do
  post "teams/:id" => "teams#show"
  post "ideas/:id" => "ideas#show"
  resources :ideas
  resources :users do 
    member do 
      get :following, :followers
    end
  end 
  resources :teams
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :walls do
    resources :wallposts
  end 
  resources :messageboards do
    resources :messages
  end 
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via:'get'
  match '/about', to: 'static_pages#about', via:'get'
  match '/contact', to: 'static_pages#contact', via:'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :user
	validates :name, presence: true, length: {maximum: 50}
	validates :description, presence: true
	validates :user_id, presence: true
	belongs_to :team
	has_many :requirements
	has_many :skills, through: :requirements
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

	def index
		@ideas=Idea.paginate(page: params[:page], per_page: 20)
	end

	def show
		@idea=Idea.find(params[:id])
		@user=@idea.user
		@team=@idea.team
		if params[:name] != nil
      		team = Team.find_by(name: params[:name])
     		if @idea.team.blank?
     			@idea.update(team_id: team.id)
        		redirect_to @idea
     		end
    	end 
	end

	def new 
		@idea= Idea.new
	end

	def create
		@idea= Idea.new(idea_params)
		if @idea.save
			Skill.count.times do |i|
        		unless params[:skill]==nil
        			if params[:skill][i.to_s] =='1'
              		@idea.requirements.create!(idea_id: @idea.id, skill_id: (i+1))
        			end
        		end
            end
			flash[:success]="Idea Created"
			redirect_to @idea
		else
			render 'new'
		end
	end

	def edit
    	@idea = Idea.find(params[:id])
	end

	def update
    	@idea = Idea.find(params[:id])
		if @idea.update_attributes(idea_params)
			Skill.count.times do |i|
        		unless params[:skill]==nil
        			if params[:skill][i.to_s] =='1'
              		@idea.requirements.create!(idea_id: @idea
              			.id, skill_id: (i+1))
        			end
        		end
            end
			flash[:success] = "Idea Updated"
			redirect_to @idea
		else
			render 'edit'
		end
	end

	def destroy
		Idea.find(params[:id]).destroy
		flash[:success] = "Idea Deleted"
		redirect_to ideas_url
	end

	private 



	def idea_params
		params.require(:idea).permit(:name, :user_id, :description)
	end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

    <%=f.hidden_field :user_id, value: current_user.id %>

app/views/ideas/_idea.html.erb
	<li>

      <%= link_to idea.name, idea %>
        <% if current_user.admin? || current_user?(User.find(idea.user_id)) %>
   		 | <%= link_to "delete", idea, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
	</li>

app/views/ideas/edit.html.erb
<% provide(:title, "Edit idea") %>
<h1>Update your idea</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@idea) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= render 'shared/checkbox_form' %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>

    <% end %>

    
  </div>
</div>

app/views/ideas/index.html.erb
<% provide(:title, 'Ideas') %>
<div class="hero-unit">
	<h1>Ideas</h1>
<div class="text-right">
<%= link_to "Create Idea", new_idea_path, class: "btn btn-small btn-primary" %>
</div>
	<div class="pagination-right">
	<%= will_paginate %>
	</div>

	<ul class="users">
	   <%= render @ideas %>
	</ul>

	<div class="pagination-right">
	<%= will_paginate %>
	</div>
</div>

app/views/ideas/new.html.erb
<% provide(:title, 'Create Idea') %>
<h1>Create Idea</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@idea) do |f| %>
      <%= render 'fields', f: f %>
      <%= render 'shared/checkbox_form' %>
      <%= f.submit "Create my idea", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/ideas/show.html.erb
<% provide(:title, @idea.name) %>
      
   <div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @idea.name %>
      </h1>
    </section>
    <section class="users">
     Author: <%= render @user %>
    </section>
   <%unless @idea.team.blank? %>
    <section>
      Team: <%= render @team %>
    </section>
    <%end%>
     <section>
      <%= render 'shared/new_project_form' %>
    </section>
    <section>
    <b>Requirements: (<%=@idea.requirements.count %>) </b> 
    <%= render 'shared/idea_requirements' %>
    </section>
        </aside>
  <div class="text-center hero-unit span6 pull-right">
    <aside>
      <h3><%=@idea.name%> Description</h3>
      <%= @idea.description %>
    </aside>
    <%if current_user==@user%>
    <aside class="text-right">
     <%= link_to "Edit", edit_idea_path, class: "btn btn-small btn-primary" %>
     </aside>
     <%end%>
  </div>
  <div class="hero-unit span6 pull-right">
    <h3> Comments </h3>
      
      </div>
</div>