config/routes.rb
SampleApp::Application.routes.draw do
  post "teams/:id" => "teams#show"
  post "ideas/:id" => "ideas#show"
  resources :ideas
  resources :users do 
    member do 
      get :following, :followers
    end
  end 
  resources :teams
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :walls do
    resources :wallposts
  end 
  resources :messageboards do
    resources :messages
  end 
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via:'get'
  match '/about', to: 'static_pages#about', via:'get'
  match '/contact', to: 'static_pages#contact', via:'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :user
	validates :name, presence: true, length: {maximum: 50}
	validates :description, presence: true
	validates :user_id, presence: true
	belongs_to :team
	has_many :requirements
	has_many :skills, through: :requirements
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :user
	belongs_to :team
	validates :team_id, presence: true
	validates :user_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :messageboard
  belongs_to :user
  default_scope -> { order('created_at DESC')}
  validates :content, presence: true, length: { maximum: 250 }
end

app/models/messageboard.rb
class Messageboard < ActiveRecord::Base
	belongs_to :team 
	has_many :messages
	validates :team_id, presence: true
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  # Returns microposts from the users being followed by the given user.
  def self.from_users_followed_by(user)
    followed_user_ids = "SELECT followed_id FROM relationships
                         WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id",
          user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/requirement.rb
class Requirement < ActiveRecord::Base
	belongs_to :ideas
	belongs_to :skills
end

app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :skillsets
	has_many :users, through: :skillsets
	validates :name, presence: :true 
	has_many :requirements
	has_many :ideas, through: :requirements
end

app/models/skillset.rb
class Skillset < ActiveRecord::Base
	belongs_to :skills
	belongs_to :users
	validates :user_id, presence: true
	validates :skill_id, presence: true

	
end

app/models/team.rb
class Team < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :ideas
	has_many :memberships, dependent: :destroy
	has_many :users, through: :memberships
	has_one :messageboard, dependent: :destroy
	validates :name, presence: true, length: { maximum: 50 },
					uniqueness: { case_sensitive: false }


end

def join_team!(user)
	memberships.create!(user_id: user.id)
end 

app/models/user.rb
class User < ActiveRecord::Base
	has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                   class_name:  "Relationship",
                                   dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  has_one :wall, dependent: :destroy
  has_many :wallposts, dependent: :destroy
  has_and_belongs_to_many :teams
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :messages
  has_many :ideas 
  has_many :skillsets
  has_many :skills, through: :skillsets



  before_save{ self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  									uniqueness: { case_sensitive: false }
  has_secure_password
 	validates :password, length: { minimum: 6 }

  def addMember(user) 
    @team.users << user
  end

 	def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    Micropost.from_users_followed_by(self)
  end


  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end 

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end 

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end 

  def member?(team)
    memberships.find_by(team_id: team.id)
  end 

  def leave_team!(team)
    memberships.find_by(team_id: team.id).destroy
  end 

   def findSkill(user)
    skills = []
    user.skillsets.each do |skillset|
      skills.push(Skill.find(skillset.skill_id).name)
    end 
    skills
  end

  private

  	def create_remember_token
  		self.remember_token = User.digest(User.new_remember_token)
  	end
end

app/models/wall.rb
class Wall < ActiveRecord::Base
	belongs_to :user
	has_many :wallposts
	validates :user_id, presence: true
end

app/models/wallpost.rb
class Wallpost < ActiveRecord::Base
  belongs_to :wall
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :content, presence: true, length: { maximum: 250 }
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
  	@current_user = user
  end

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end 

  def current_user?(user)
    user == current_user
  end

  def signed_in? 
  	!current_user.nil?
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please Sign In."
    end
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/skillsets_helper.rb
module SkillsetsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 42 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def gravatar_small(user, options = { size: 20 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  def findSkill(user)
    skills = []
    user.skillsets.each do |skillset|
      skills.push(Skill.find(skillset.skill_id).name)
    end 
    skills

  end
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Puzzle Piece", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Teams", teams_path %></li>
            <li><%= link_to "Ideas", ideas_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  </head>
  <body>
   <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %> 
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_checkbox_form.html.erb
<% Skill.count.times do |i| %>
  <%= label_tag Skill.find(i+1).name %>
  <%= check_box_tag "skill[#{i}]" %> <br />
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items, inner_window: 1 %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= feed_item.content %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.content %>
  <% end %>
</li>   

app/views/shared/_idea_requirements.html.erb
<% @user ||= current_user %>
 <div class="user">
 	<% skills = [] %>
 	<% @idea.requirements.each do |requirement| %>
 		<% skills.push(Skill.find(requirement.skill_id).name) %>
 	<% end %>
 	<% skills.each do |skill| %>
 		<div class="text-success">
 		<%= skill %>
 		</div>
 	<% end %>

 
 

app/views/shared/_idea_stats.html.erb
<% @user ||= current_user %>
<div class='team_stats'>
 
    <strong id="Ideas" class="stat">
      <%= @user.ideas.count %> Ideas
      
    </strong>
 </div>
 <div class="user">
 <%= render  @ideas  %>
 </div>
 <% if current_user==@user %>
  <%= link_to "Create Idea", new_idea_path, class: "btn btn-medium btn-primary white"   %>
<%end%>

app/views/shared/_message_form.html.erb
<%= form_for([@messageboard,@message]) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write a message..." %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <%= f.submit "Post", class: "btn btn-small btn-primary" %>
<% end %>

app/views/shared/_messages.html.erb
<% @messages.each do |message| %>
  <ol class="microposts">
  <span class="user">
    <%= link_to gravatar_small(User.find(message.user_id)), User.find(message.user_id) %>
    <%= link_to User.find(message.user_id).name, User.find(message.user_id) %>
    </span>
    <span class="content">
    <%= message.content %>
    </span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(message.created_at) %> ago.
    </span>
  </ol>
<% end %> 

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose a new status..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_new_member_form.html.erb
   <%= form_tag do %>
  		<%= label_tag "Add a Member To Your Team"  %>
      	<%= text_field_tag :email,nil, placeholder: "email" %>
        <%= submit_tag "Add Member", class: "btn btn-medium btn-primary" %>
    <% end %>

app/views/shared/_new_project_form.html.erb
  <%= form_tag do %>
  		<%= label_tag "Give your Idea to a Team"  %>
      	<%= text_field_tag :name ,nil, placeholder: "Team name" %>
        <%= submit_tag "Assign Team", class: "btn btn-medium btn-primary" %>
    <% end %>

app/views/shared/_skills_stats.html.erb
<% @user ||= current_user %>
<div class='team_stats'>
 
    <strong id="Ideas" class="stat">
      <%= @user.skillsets.count %> Skills
      
    </strong>
 </div>
 <div class="user">
 	<% skills = [] %>
 	<% @user.skillsets.each do |skillset| %>
 		<% skills.push(Skill.find(skillset.skill_id).name) %>
 	<% end %>
 	<% skills.each do |skill| %>
 		<div class="text-success">
 		<%= skill %>
 		</div>
 	<% end %>

 

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= current_user.microposts.count %> News Feed Items
</span>